# TUPLE

# COLLECTION ON ELEMENTS
# INCLOSED WITH()
# COMMA(,) SEPERATED ELEMENTS
# ORDERED COLLECTION
# INDEXING SUPPORT
# SLICING SUPPORTED
# DUPLICATTION ALLOWED
# IMMUTABLE IN NATURE

# METHODS IN TUPLE ARE INDEX AND COUNT

l=eval(input("Enter any tuple:"))
print(l.index(2))
print(l.count(3))                  




